import { getCurrentSession } from "@/lib/cache/session";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Outfit - account",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { user } = await getCurrentSession();
  if (!user) redirect("/auth/login");

  return (
    <>
      <div className="min-h-screen p-4 grid place-items-center">{children}</div>
    </>
  );
}
